<a href="https://colab.research.google.com/github/Colosolizer/Carisurg_Week_0_Portfolio/blob/main/Carisurg_week0_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Python Version Check
import sys
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [3]:
#Google Drive Intialization
from google.colab import drive
drive.mount('/content/drive')
print("Your Google Drive has been sucessfully mounted.")

Mounted at /content/drive
Your Google Drive has been sucessfully mounted.

In [5]:
#Library Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
priont("Libraries Imported")

Libraries Imported

In [9]:
#Dataset Loading
FILE_PATH = '/content/drive/MyDrive/Colab Notebooks/Carisurg_2026/EmergencyTriageDataset_Reduced_Dirty.csv'
df_raw = pd.read_csv(FILE_PATH)
print("Dataset Loaded")
print(f"The Following {df_raw.shape[0]} rows x {df_raw.shape[1]} Dataset with the follwing columns have been found: {list(df_raw.columns)}")

Dataset Loaded
The Following 2205 rows x 11 Dataset with the follwing columns have been found: ['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

In [10]:
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [11]:
#Data Type Check
print(df_raw.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

In [13]:
#Cleaning Gender Column, Determining unique values and counts
print(f"Total number of unique values: {df_raw['Gender'].nunique()}")
print(f"Unique values: {df_raw['Gender'].unique()}")

#Counting number of each values
print("Number of each value:")
print(df_raw['Gender'].value_counts())

Total number of unique values: 6
Unique values: ['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']
Number of each value:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [16]:
#Variant Map

gender_map = {
    'Male' : 1,
    'Female' : 0,
    'MALE' : 1,
    'FEMALE' : 0,
    '1' : 1,
    '0' : 0
}

df_raw['Gender_cleaned'] = df_raw['Gender'].map(gender_map)

#Cleaning Verification
print("Cleaned Gender:")
print(df_raw['Gender_cleaned'].value_counts())

#Showcase Null Values if any
print(f"\nNaN value count: {df_raw['Gender_cleaned'].isnull().sum()}")

Cleaned Gender:
Gender_cleaned
1    1176
0    1029
Name: count, dtype: int64

NaN value count: 0

In [17]:
#Removing Dirty Column
df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'Gender_cleaned' : 'Gender'})

print("Dirty Column Removed")
print("Gender column after cleaning:")
print(df_raw['Gender'].value_counts())
print(f"Data type: {df_raw['Gender'].dtypes}")
df_raw.head()

Dirty Column Removed
Gender column after cleaning:
Gender
1    1176
0    1029
Name: count, dtype: int64
Data type: int64

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0       0
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0       1
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0       0
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0       0
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0       0